### ISSUE TITLE
画像の大きさが大きすぎる

### ISSUE THREAD

**Issue by unillr** [Chahaaaaan/Hakuyo-Warai#40]
当たり判定が大きすぎるので小さくします

**Comment by fuu38** [comment]
本当に線の部分だけしか当たり判定要らないとかそういう話？(めんどくさくて四角形でトリミングしてごめん...)

**Comment by unillr** [comment]
@Chahaaaaan 四角形でいいけど今だと線の周りの余白が大きすぎて、重なっている部分が選択しにくいかなって

**Comment by fuu38** [comment]
なるほど
