### ISSUE TITLE
素材に対してdraggableを付与してうまいことできるようにする

### ISSUE THREAD

**Issue by fuu38** [Chahaaaaan/Hakuyo-Warai#9]

**Comment by fuu38** [comment]
index.jsにsetImage関数を作ったのでそこに組み込むのが一番簡単かなと思う

**Comment by tmtmNasubi** [comment]
了解。やってみます。

**Comment by fuu38** [comment]
@tmtmNasubi 作ったとは言ってもまだマージしてないけどね()
ブランチを既に分けてるならcherry-pickとかして変更を取り込むといいと思う.
とにかく作業の前に先にPRのマージを済ませてしまったほうがいいと思います
